### ISSUE TITLE
Is this repository alive?

### ISSUE THREAD

**Issue by artyomtrityak** [Atlantis-PBEM/Atlantis#24]
So i am wondering is this repo alive?

**Comment by Loriaki** [comment]
Hello,


yes it is still alive … 

even though the last messages have not been worked on, which is just an issue of time …

**Comment by artyomtrityak** [comment]
@Loriaki this is very good news. Are you interested in upcoming changes, travis, tests etc?

**Comment by sgb** [comment]
Actually, the reason the last few messages haven't been worked on is because they weren't very well thought out - Enno decided to run some code analysis tools over the source, and submitted some changes based on those without testing them, which resulted in the game running at http://www.shadowlandgames.com/ breaking.  Since he hadn't bothered testing his submissions, we haven't bothered incorporating them!

I do have a couple of changes pending that I want to do some more testing on before I push them (changes to economy.cpp and gamedata.cpp), but this is an open source project so submissions are welcome.

Do note that this is a very old project, which while it may not have been on github all this time, was actually started in 2001, and has changes by me dating back to at least 2002; possibly earlier.  As such there's a lot of history, and we've seen quite a few people wanting to come through and make sweeping changes, but in some notable cases those changes have not been followed through well, which is why we can be a tad skeptical at times.  Sorry if you get caught in that, but do please test things before submitting them!

As far as Gitter goes, I hadn't even heard of it before, which is possibly part of the reason it isn't integrated.  We do have an email list (http://games.groups.yahoo.com/group/atlantisdev/), which you would be welcome to join.  It's been quiet for a while, but then the code is pretty stable.

Also, I'm in Australia, so if you post a request in the middle of my night and then wonder if the project is abandoned because you haven't got a response three hours later, you may need to learn patience :-)

**Comment by artyomtrityak** [comment]
@sgb sorry for bothering, sleep well :)
So why i was asking - for first look i saw few pending pull requests for many days without any activity so i've assumed this repo collaborators are inactive. Thanks for your explanation, this really make sense. Yahoo group is pretty much dead this why i was thinking about any other channel.

P.S. and i am really happy this repo is not dead as yahoo group is.

**Comment by sgb** [comment]
The Yahoo group isn't so much dead as very very stable!

If you ask a question there you'll likely get a number of answers.

May I ask how you discovered Atlantis?

**Comment by artyomtrityak** [comment]
@sgb i was playing Atlantis many many years ago and for many years i was thinking how great the game is.

Game is great, balanced and so interesting (and nostalgic) if we would compare to current games available but not so friendly for playing it.

###(Offtopic)
About my background - i am doing JavaScript and frontend development something around 8 years.

...So i've started working on web-based Atlantis client which uses Node.js app as proxy to this Atlantis core app.

**Comment by artyomtrityak** [comment]
where latest standard rules can be found?

**Comment by sgb** [comment]
>
> where latest standard rules can be found?
>
# make
# cd standard
# ./standard genrules standard_intro.html html/standard.css rules.html

Steve.

**Comment by artyomtrityak** [comment]
@sgb thanks!

**Comment by artyomtrityak** [comment]
Does anyone have some big turn report for latest Atlantis version? I am writing JS parser and need to test all works fine

**Comment by Loriaki** [comment]
i will check if i have still reports of rest games. be aware some parts are spcific to the gamesetup.

**Comment by artyomtrityak** [comment]
@Loriaki that's fine, i will test with game by myself anyway but big report will help

**Comment by artyomtrityak** [comment]
sorry for boring you but any big report will very very help :)

**Comment by artyomtrityak** [comment]
Just to remind - are left / right, top / bottom map edges connected? So i can go from 0,0 to 120,0 and to 0,120? (if map is 120x120 for example)?

**Comment by sgb** [comment]
>
> Just to remind - are left / right, top / bottom map edges connected? So i
> can go from 0,0 to 120,0 and to 0,120? (if map is 120x120 for example)?
>
By default, east and west (left and right) are connected, but north and
south (top and bottom) are not.  However, if you're pondering map
representations, do consider the possibility that a game is using the
ICOSAHEDRAL_WORLD setting.

Steve.

**Comment by Loriaki** [comment]
On Tue, May 03, 2016 at 06:50:04PM -0700, Stephen Baillie wrote:
> >
> > Just to remind - are left / right, top / bottom map edges connected? So i
> > can go from 0,0 to 120,0 and to 0,120? (if map is 120x120 for example)?
> >
> By default, east and west (left and right) are connected, but north and
> south (top and bottom) are not.  However, if you're pondering map
> representations, do consider the possibility that a game is using the
> ICOSAHEDRAL_WORLD setting.

I once tried to figure out, hou to get a growing map with uncrossable 
Regiontypes as borders, so there region types could be changed after a
certain amount of time ... but there are the sublayers too ...

**Comment by artyomtrityak** [comment]
@sgb ok thx.

**Comment by snowgoon88** [comment]
Hello,
I wanted to say that on my 'fork', the repo is alive. For helping our GM, I'm developping a graphic interface to vizualise the word and edit it. I've also wirtten a tool to add new levels (mostly underword and underdeep) to an existing game.

Snow (aka Alain)

**Comment by Loriaki** [comment]
On Wed, Oct 26, 2016 at 03:59:32AM -0700, snowgoon88 wrote:
> Hello,
> I wanted to say that on my 'fork', the repo is alive. For helping our GM, I'm
> developping a graphic interface to vizualise the word and edit it. I've also
> wirtten a tool to add new levels (mostly underword and underdeep) to an
> existing game.

Well this Repo is alive as well .. even though not much developer are with it 
currently .. 
I plan to setup a new a5 game also plans are to clean the code .. as well as
a new website ... 
help would be needed as well :-)

Loria

**Comment by artyomtrityak** [comment]
@Loriaki i can help with website

**Comment by artyomtrityak** [comment]
Alright, bumping this thread - can someone give me permissions to create new repositories inside this Org? I want to add game clients (AtlaClient, ALH, Advisor) here, battle simulator.

BTW i have created website - http://atlantis-pbem.com
I'm using it for latest game but we can expand it with general details about this repo, development etc.

**Comment by Loriaki** [comment]
i am quite busy, hope i can answer next week

**Comment by artyomtrityak** [comment]
@Loriaki thanks! that would be awesome

**Comment by jt-traub** [comment]
Obviously this repo is alove and this is just an old and now dead issue.
