### ISSUE TITLE
Problem with wages, maxwages ?? [still economy.cpp]

### ISSUE THREAD

**Issue by snowgoon88** [Atlantis-PBEM/Atlantis#26]
I was trying to edit the maxwages of a region using the "editor" and came upon a strange "behavior" (or piece of code).

basically, you can not change maxwages as it is automatically recomputed later in 
`void ARegion::UpdateEditRegion() [economy.cpp]`
that calls
`void ARegion::SetIncome() [economy.cpp]`

Is it the desired behavior of the code ? Or the fact that economy.cpp was rewritten is the cause of this unwanted behavior ?

I'm asking this because there is some strange piece of code in this last function... maxwages is both a local and class variable for example. 

If the behavior is not wanted, I can try to fix it (and clean up / rewrite) some small parts of economy.cpp once I take the time to undestand how wages and economy work...

**Comment by jt-traub** [comment]
Interestingly enough, I think this is correct (given the code).  It does make the ability to edit ma xwages in the editor weird, but given how wages are defined, that's probably for the best honestly.

Basically the code sets the maxwages (the first call) and then just uses a local variable which shadows that class variable for other calculations since the *actual* maxwages in the hex aren't going to change after that initially setup.   Closing since this isn't going to be changed.
